# Project settings and configuration.

import argparse
import os
from dataclasses import dataclass, asdict
from typing import Optional


"""
LLM Config
----------
Qwen models support the "system" role for the chat template.
gemma-2-it does NOT support a system role, so system instructions must be prepended to the user prompt instead.
use_system_prompt is used to determine which prompt template to use for a given model.
"""


LLM_CONFIGS = {
    "Qwen/Qwen2.5-0.5B-Instruct": {"use_system_prompt": True},
    "Qwen/Qwen2.5-1.5B-Instruct": {"use_system_prompt": True},
    "Qwen/Qwen2.5-3B-Instruct":   {"use_system_prompt": True},
    "Qwen/Qwen2.5-7B-Instruct":   {"use_system_prompt": True},
    "google/gemma-2-2b-it":       {"use_system_prompt": False},
}


# defining the system prompt if the LLM supports it, otherwise the system prompt is prepended to the user prompt
def get_use_system_prompt(llm_name: str) -> bool:
    if llm_name in LLM_CONFIGS:
        return LLM_CONFIGS[llm_name]["use_system_prompt"]
    return "gemma" not in llm_name.lower()


@dataclass
class RunConfig:
    # Dataset
    dataset_source: str = "bright"          # "bright" or "beir"
    dataset_name: str = "psychology"
    split: str = "test"                     # used when dataset_source == "beir"

    use_subset: bool = True
    corpus_subset_size: int = 20000
    max_queries: Optional[int] = 100        # None = use all queries with qrels
    top_k_retrieve: int = 100

    # Models
    llm_name: str = "Qwen/Qwen2.5-7B-Instruct"
    llm_backend: str = "ollama"       # "transformers" or "ollama"
    ollama_host: str = "http://localhost:11434"
    ollama_model: str = "qwen2.5:7b"
    dense_model_name: str = "multi-qa-MiniLM-L6-cos-v1"
    cross_encoder_name: str = "cross-encoder/ms-marco-MiniLM-L-6-v2"

    # Agent / retrieval hyperparameters
    rrf_k: int = 60
    tool_k: int = 50
    rerank_depth: int = 25
    judge_snippets: int = 3
    snippet_chars: int = 200
    max_new_tokens: int = 96
    max_refine: int = 2
    enable_decomposition: bool = False
    max_subqueries: int = 3

    # Run control
    random_seed: int = 42
    output_dir: str = "outputs"
    hf_token: Optional[str] = None
    device: Optional[str] = None            # None = auto-detect (cuda if available)
    demo_query: bool = True
    save_traces: bool = True
    log_level: str = "INFO"

    def to_dict(self) -> dict:
        return asdict(self)


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="run.py",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    data = p.add_argument_group("Dataset")
    data.add_argument("--dataset-source", choices=["bright", "beir"], default="bright")
    data.add_argument("--dataset-name", default="psychology")
    data.add_argument("--split", default="test")
    data.add_argument("--no-subset", dest="use_subset", action="store_false")
    data.add_argument("--corpus-subset-size", type=int, default=20000)
    data.add_argument("--max-queries", type=int, default=100)
    data.add_argument("--top-k-retrieve", type=int, default=100)

    model = p.add_argument_group("Models")
    model.add_argument("--llm-name", default="Qwen/Qwen2.5-3B-Instruct")
    model.add_argument("--llm-backend", choices=["transformers", "ollama"], default="ollama")
    model.add_argument("--ollama-host", default="http://localhost:11434")
    model.add_argument("--ollama-model", default="qwen2.5:7b")
    model.add_argument("--dense-model", dest="dense_model_name",
                        default="multi-qa-MiniLM-L6-cos-v1")
    model.add_argument("--cross-encoder-name",
                        default="cross-encoder/ms-marco-MiniLM-L-6-v2")

    agent = p.add_argument_group("Agent / Retrieval Parameters")
    agent.add_argument("--rrf-k", type=int, default=60) # RRF damping constant
    agent.add_argument("--tool-k", type=int, default=50) # Candidates each retrieval tool returns.
    agent.add_argument("--rerank-depth", type=int, default=25) # How many candidates cross_encoder_rerank re-scores.
    agent.add_argument("--judge-snippets", type=int, default=3) # Top docs shown to the judge step.
    agent.add_argument("--snippet-chars", type=int, default=200) # Chars per snippet shown to the judge.
    agent.add_argument("--max-new-tokens", type=int, default=96) # Max new tokens generated per LLM call.
    agent.add_argument("--max-refine", type=int, default=2) # Max self-correction iterations executed by the agent.
    agent.add_argument("--enable-decomposition", action="store_true") # Enable query decomposition.
    agent.add_argument("--max-subqueries", type=int, default=3) # Max sub-queries generated by the agent when decomposition is enabled.

    misc = p.add_argument_group("Run control")
    misc.add_argument("--seed", dest="random_seed", type=int, default=42)
    misc.add_argument("--output-dir", default="outputs")
    misc.add_argument("--hf-token", default=os.environ.get("HF_TOKEN"))
    misc.add_argument("--device", default=None)
    misc.add_argument("--no-demo", dest="demo_query", action="store_false")
    misc.add_argument("--no-save-traces", dest="save_traces", action="store_false")
    misc.add_argument("--log-level", default="INFO",
                       choices=["DEBUG", "INFO", "WARNING", "ERROR"])

    p.set_defaults(use_subset=True, demo_query=True, save_traces=True)
    return p


def parse_config_from_args(args: argparse.Namespace) -> RunConfig:
    """
    Build a RunConfig from parsed arguments.
    """
    max_queries = args.max_queries
    if max_queries is not None and max_queries <= 0:
        max_queries = None

    return RunConfig(
        dataset_source=args.dataset_source,
        dataset_name=args.dataset_name,
        split=args.split,
        use_subset=args.use_subset,
        corpus_subset_size=args.corpus_subset_size,
        max_queries=max_queries,
        top_k_retrieve=args.top_k_retrieve,
        llm_name=args.llm_name,
        llm_backend=args.llm_backend,
        ollama_host=args.ollama_host,
        ollama_model=args.ollama_model,
        dense_model_name=args.dense_model_name,
        cross_encoder_name=args.cross_encoder_name,
        rrf_k=args.rrf_k,
        tool_k=args.tool_k,
        rerank_depth=args.rerank_depth,
        judge_snippets=args.judge_snippets,
        snippet_chars=args.snippet_chars,
        max_new_tokens=args.max_new_tokens,
        max_refine=args.max_refine,
        enable_decomposition=args.enable_decomposition,
        max_subqueries=args.max_subqueries,
        random_seed=args.random_seed,
        output_dir=args.output_dir,
        hf_token=args.hf_token,
        device=args.device,
        demo_query=args.demo_query,
        save_traces=args.save_traces,
        log_level=args.log_level,
    )


def parse_config(argv=None) -> RunConfig:
    args = build_arg_parser().parse_args(argv)
    return parse_config_from_args(args)
